### ISSUE TITLE
ChangeableText.tsx(Atom)의 재사용성 저하

### ISSUE THREAD

**Issue by plantstoen** [readlight/readlight-landing#12]
Atom컴포넌트 안에 다음과 같이 직접 고정적인 데이터를 저장하고 받아오는 props로 변경해서 사용함
`const textData = [
    '하루 한권, 인공지능이 당신의 독서 취향을 분석해 책을 추천해줍니다.',
    '리드라이트 큐레이터들이 최근의 이슈나 트렌드에 맞는 책들을 엄선해 제공합니다.',
    '독서 결정에 도움을 줄수 있도록 큐레이터가 책을 읽고 작성한 칼럼을 제공합니다.',
  ];`

-> 상위 컴포넌트에서 받아올수 있도록 변경 필요

**Comment by xodus0721** [comment]
수정 완료했습니다.
