### ISSUE TITLE
사용된 Enum타입들을 number mapping에서 string mapping으로 바꾸기

### ISSUE THREAD

**Issue by plantstoen** [readlight/readlight-landing#18]
장기적인 관점에서 봤을 때 로직을 제어하기 더 어렵게 만들 것 같음

참고
https://luckyyowu.tistory.com/401

**Comment by xodus0721** [comment]
현재 FeatureList.ts 만 string mapping으로 바꿨습니다.

**Comment by plantstoen** [comment]
그렇군요.. 다른 Enum이 쓰인곳을 확인하고 바꾸면 될거 같은데, 아마 useScrollEvent 그 훅에서 쓰일거에요 scrollDirection을 Enum으로 한것 같습니다. 근데 지금 그 훅이 initializing문제도 있고, 슬랙에서 말하셨던 가독성 저하도 있어서 헤더를 항상 흰색(스크롤된 상태)로 놓고 그냥 그 훅은 레거시로 남겨만 놓는건 어떨까요??

**Comment by xodus0721** [comment]
근데 scrollDirecton을 단순히 string으로 바꿨는데 아무렇지도 않게 잘 동작하더군요..?

**Comment by plantstoen** [comment]
왜냐면 scrollDirection을 쓰는곳이 없을 걸요..?

**Comment by xodus0721** [comment]
아하.. ㅋㅋㅋㅋ 그럼 일단 커밋할게요
