### ISSUE TITLE
Props받아오는 것을 type에서 interface로 바꾸기

### ISSUE THREAD

**Issue by plantstoen** [readlight/readlight-landing#26]
저번 커밋에 포함되어 있는 내용인데 issue등록을 안해놨네요
-> 보니까 utils/Emoji.tsx같은데 보면 아직 type으로 되있는거 보면 모든 파일이 다 바뀐건 아닌거 같습니다

**Comment by plantstoen** [comment]
확인했습니다. 일단 그러면 이 이슈는 닫도록 할게요!

**Comment by plantstoen** [comment]
아 닫혀져 있네,,,ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ

**Comment by xodus0721** [comment]
zzzzzzzzzzzzzzzz
